'use strict';
document.getElementById('year').textContent = new Date().getFullYear();
document.querySelectorAll('[data-demo]').forEach(button => button.addEventListener('click', () => {
  const demo = NEXC.demos[Number(button.dataset.demo)];
  document.querySelectorAll('[data-demo]').forEach(b => {b.classList.toggle('active', b === button);b.setAttribute('aria-pressed', String(b === button));});
  document.getElementById('demo-prompt').textContent=demo.prompt;
  document.getElementById('demo-title').textContent=demo.title;
  document.getElementById('demo-text').textContent=demo.text;
  document.getElementById('demo-items').replaceChildren(...demo.items.map((item,index)=>{const span=document.createElement('span');span.textContent=`0${index+1}　${item}`;return span;}));
}));

const $ = selector => document.querySelector(selector);
const escapeHTML = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const courseById = id => NEXC.courses.find(course => course.id === id);
const modal = $('#modal');
let lastFocused;

function courseCard(course) {
  return `<article class="course-card"><a href="#course/${course.id}" class="course-art ${course.color}" aria-label="${course.title} 상세 보기"><div class="art-top"><span>NEXC AI CLASS</span><span>0${NEXC.courses.indexOf(course)+1}</span></div><div class="art-title">${course.category}<span>${course.symbol}</span></div><div class="art-caption">${course.short}</div></a><div class="course-content"><div class="course-meta">${course.category} <span>실습 중심 교육</span></div><a href="#course/${course.id}"><h3>${course.title}</h3></a><p>${course.description}</p><div class="course-tags">${course.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="course-actions"><button data-action="apply" data-course="${course.id}">강의 신청하기 ↗</button><a href="#ebook/${course.id}">E-BOOK 보기</a></div></div></article>`;
}
function renderCourses(filter='all') {
  $('#course-grid').innerHTML=NEXC.courses.filter(c=>filter==='all'||c.id===filter).map(courseCard).join('');
}
renderCourses();
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{
  document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});
  renderCourses(button.dataset.filter);
}));

const audiences = [
  {name:'시니어',symbol:'☺',title:'천천히, 함께 시작해요.',text:'컴퓨터가 익숙하지 않아도 괜찮습니다. 일상에 필요한 AI부터 하나씩 배웁니다.',topics:'스마트폰 AI 활용 · 쉬운 질문법 · 일상 콘텐츠'},
  {name:'기업',symbol:'▥',title:'팀의 일하는 방식이 달라집니다.',text:'기획부터 마케팅, 반복 업무까지. 조직의 업무에 맞춘 실무형 교육을 설계합니다.',topics:'업무 생산성 · 콘텐츠 기획 · 문서 자동화'},
  {name:'교육자',symbol:'▤',title:'배움의 경험을 더 풍부하게.',text:'수업 자료와 이미지, 교육 콘텐츠 제작에 AI를 활용하는 방법을 배웁니다.',topics:'강의자료 제작 · 교수학습 설계 · AI 리터러시'},
  {name:'공무원',symbol:'▦',title:'행정에 실용적인 변화를.',text:'보고서와 기획 문서, 자료 정리와 홍보까지. 행정업무에 필요한 AI를 배웁니다.',topics:'보고서 작성 · 정책자료 정리 · 공공 홍보'}
];
$('#remaining-sections').innerHTML=`
<section class="audience-section" id="audience"><div class="wrap section"><div class="section-head"><div><div class="eyebrow">AI FOR EVERYONE</div><h2>시작점이 달라도,<br><span>가능성은 누구에게나.</span></h2></div><p>경험과 목적에 맞춰 배우세요.<br>당신에게 맞는 속도로 함께합니다.</p></div><div class="audience-grid">${audiences.map(a=>`<article class="audience-card"><span class="audience-icon" aria-hidden="true">${a.symbol}</span><h3>${a.name} AI 교육</h3><strong>${a.title}</strong><p>${a.text}</p><small>${a.topics}</small><button class="text-link" data-action="audience" data-audience="${a.name}">${a.name} 교육 알아보기 <span>↗</span></button></article>`).join('')}</div></div></section>
<section class="wrap section" id="organization"><div class="organization-box"><div><div class="eyebrow">FOR YOUR ORGANIZATION</div><h2>우리 조직에 꼭 맞는<br><span>AI 교육이 필요하신가요?</span></h2><p>교육 대상과 현장의 업무를 이해하고,<br>실제로 활용할 수 있는 맞춤형 프로그램을 제안합니다.</p><button class="button primary" data-action="organization">기업·기관 강연 문의하기 ↗</button></div><div class="organization-steps"><div><span>01</span><div><strong>목표를 함께 찾습니다</strong><p>교육 대상, 업무 특성, 필요한 역량 파악</p></div></div><div><span>02</span><div><strong>현장에 맞게 설계합니다</strong><p>수준·일정·인원에 맞춘 커리큘럼 구성</p></div></div><div><span>03</span><div><strong>직접 만들며 배웁니다</strong><p>실제 업무와 연결하는 실습 중심 교육</p></div></div></div></div><div class="organization-types"><span>기업</span><span>공공기관</span><span>학교·대학</span><span>지자체·협회</span><span>교육기관</span></div></section>
<section class="books-section" id="ebooks"><div class="wrap section"><div class="section-head"><div><div class="eyebrow">KEEP LEARNING</div><h2>배움은 계속됩니다. <span>NEXC E-BOOK</span></h2><p>강의에서 배운 내용을, 나만의 속도로 다시 꺼내 보세요.</p></div><span class="status-label">출간 준비 중</span></div><div class="ebook-filters filter-row" role="group" aria-label="전자책 분야"><button class="chip active" data-book-filter="all" aria-pressed="true">전체 E-BOOK</button>${NEXC.courses.map(c=>`<button class="chip" data-book-filter="${c.id}" aria-pressed="false">${c.category}</button>`).join('')}</div><div class="book-grid" id="book-grid"></div></div></section>
<section class="wrap section free-section" id="free"><div><div class="eyebrow">YOUR FIRST STEP</div><h2>AI와 친해지는<br><span>가벼운 첫걸음.</span></h2><p>지금 읽고, 바로 시도하는 무료 학습 자료입니다.<br>공개 영상 강의는 준비 중입니다.</p></div><div class="free-resources"><button class="resource-card" data-action="lesson"><span class="resource-icon">✦</span><span><small>무료 미니 레슨 · 생성AI</small><strong>좋은 답변을 만드는 질문의 4가지 요소</strong><span>역할, 목표, 맥락, 출력 형식 알아보기</span></span><b>↗</b></button><button class="resource-card" data-action="checklist"><span class="resource-icon">✓</span><span><small>무료 학습 자료 · 체크리스트</small><strong>AI 결과물, 사용 전에 확인하세요</strong><span>정확성부터 개인정보까지 점검하기</span></span><b>↓</b></button></div></section>
<section class="reviews-section" id="reviews"><div class="wrap section"><div class="section-head"><div><div class="eyebrow">LEARNING STORIES</div><h2>배움이 일상이 되는 이야기.</h2><p>AI를 배우고, 직접 활용하기 시작한 순간들을 나눕니다.</p></div></div><div class="review-empty"><span class="quote-mark">“</span><div><h3>진짜 경험을 담은 후기를 기다립니다.</h3><p>수강생의 동의를 받은 실제 후기만 게시합니다.<br>공개 가능한 수강 후기가 준비되면 이곳에서 만나보실 수 있습니다.</p><a class="text-link" href="mailto:e_iiias@naver.com?subject=NEXC%20AI%20수강%20후기%20문의">후기 전달 문의 ↗</a></div></div></div></section>
<section class="wrap section about-grid" id="about"><div class="about-brand"><span>NEXC AI</span><h2>기술을 이해하고,<br>가능성을 연결합니다.</h2><div class="about-wordmark"><img src="logo.png" alt="NEXC"><b>AI</b></div><p>AI FOR A BETTER TOMORROW</p></div><div class="about-copy"><div class="eyebrow">MEET YOUR INSTRUCTOR</div><h2>AI를 쉽게 가르치는 사람</h2><h3>장안선 <span>NEXC AI 대표 · AI 전문강사</span></h3><p>생성AI, AI 이미지, AI 영상, 업무자동화 등 실제 교육 현장에서 바로 활용할 수 있는 AI 활용법을 쉽고 실전적으로 교육합니다.</p><p>새로운 기술이 누군가에게는 새로운 기회가 되도록.<br>어려운 개념은 쉽게, 배운 내용은 바로 활용할 수 있게 안내합니다.</p><div class="about-tags"><span>생성AI</span><span>AI 이미지</span><span>AI 영상</span><span>업무자동화</span></div><button class="button outline" data-action="organization">강연 문의하기 ↗</button></div></section>
<section class="faq-section" id="faq"><div class="wrap section faq-grid"><div><div class="eyebrow">QUESTIONS & ANSWERS</div><h2>궁금한 점이<br>있으신가요?</h2><p>시작 전, 자주 묻는 질문을 확인하세요.</p><a class="text-link" href="tel:01026273771">직접 문의하기 ↗</a></div><div class="faq-list">${[
['컴퓨터를 잘 못해도 수강할 수 있나요?','네. 교육 대상과 수준에 맞춰 기초부터 단계적으로 진행할 수 있습니다. 상담 시 현재 활용 수준을 알려주시면 적합한 교육을 안내합니다.'],
['기업이나 기관도 교육을 신청할 수 있나요?','가능합니다. 교육 인원, 업무 특성, 목표에 맞춰 맞춤형 프로그램을 구성합니다. 기업·기관 강연 문의 양식을 이용해 주세요.'],
['온라인 강의도 가능한가요?','온라인과 오프라인 교육 모두 문의할 수 있습니다. 일정과 과정별 진행 방식은 상담을 통해 확정합니다.'],
['원하는 주제로 강의를 요청할 수 있나요?','네. 생성AI, 이미지, 영상, 업무자동화 등 교육 목적과 현장의 업무에 맞춘 강의 구성이 가능합니다.'],
['수강료와 교육 일정은 어떻게 확인하나요?','교육 분야, 인원, 시간, 진행 방식에 따라 달라집니다. 신청 양식에 희망 조건을 남겨 문의해 주세요. 상담 후 안내합니다.'],
['E-BOOK은 어떻게 받을 수 있나요?','현재 전자책은 출간 준비 중입니다. 판매가 시작되면 상품별 가격과 결제 방법, PDF 제공 방식을 상세 페이지에 안내합니다. 현재는 결제와 다운로드를 제공하지 않습니다.']
].map(([q,a],i)=>`<details${i===0?' open':''}><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></div></section>
<section class="contact-section" id="contact"><div class="wrap contact-inner"><div class="eyebrow">YOUR NEXT CHAPTER STARTS HERE</div><h2>더 나은 내일,<br>AI와 함께 시작하세요.</h2><p>첫 질문부터 실전 활용까지, NEXC AI가 함께합니다.</p><div class="actions"><button class="button primary" data-action="apply">수강 상담 신청하기 ↗</button><button class="button contact-outline" data-action="organization">강연 문의하기 ↗</button></div><div class="contact-links"><a href="tel:01026273771">010-2627-3771</a><span></span><a href="mailto:e_iiias@naver.com">e_iiias@naver.com</a></div></div></section>`;

function renderBooks(filter='all') {
  $('#book-grid').innerHTML=NEXC.courses.filter(c=>filter==='all'||c.id===filter).map(c=>`<article class="book-card"><a href="#ebook/${c.id}" class="book-cover ${c.color}"><span>NEXC AI · PRACTICAL GUIDE</span><h3>${c.book}</h3><span class="book-symbol" aria-hidden="true">${c.symbol}</span><small>장안선 지음 &nbsp; | &nbsp; NEXC AI</small></a><div><span class="course-meta">${c.category} · PDF 전자책</span><h3><a href="#ebook/${c.id}">${c.book}</a></h3><a href="#ebook/${c.id}" class="text-link">구성 살펴보기 ↗</a></div></article>`).join('');
}
renderBooks();
document.querySelectorAll('[data-book-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-book-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});renderBooks(button.dataset.bookFilter);}));

function openModal(title, content) {
  if(!modal.open) lastFocused=document.activeElement;
  $('#modal-title').textContent=title;
  $('#modal-body').innerHTML=content;
  if(!modal.open) modal.showModal();
  document.body.classList.add('modal-open');
}
function closeModal(){modal.close();}
$('#close-modal').addEventListener('click',closeModal);
modal.addEventListener('click',event=>{if(event.target===modal){const r=modal.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeModal();}});
modal.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(lastFocused?.isConnected)lastFocused.focus();});
$('#menu-toggle').addEventListener('click',()=>{const opened=$('#mobile-menu').hidden;$('#mobile-menu').hidden=!opened;$('#menu-toggle').setAttribute('aria-expanded',String(opened));$('#menu-toggle').setAttribute('aria-label',opened?'메뉴 닫기':'메뉴 열기');});
$('#mobile-menu').addEventListener('click',event=>{if(event.target.closest('a')){$('#mobile-menu').hidden=true;$('#menu-toggle').setAttribute('aria-expanded','false');$('#menu-toggle').setAttribute('aria-label','메뉴 열기');}});
window.addEventListener('scroll',()=>$('.site-header').classList.toggle('scrolled',scrollY>10),{passive:true});

const field = (label,name,type='text',required=true,extra='') => `<label>${label}${required?' <span class="required">*</span>':''}<input name="${name}" type="${type}" ${required?'required':''} ${extra}></label>`;
const selectField = (label,name,options,selected='') => `<label>${label} <span class="required">*</span><select name="${name}" required><option value="">선택해 주세요</option>${options.map(o=>`<option ${o===selected?'selected':''}>${o}</option>`).join('')}</select></label>`;
const consent = `<div class="consent-info">작성한 내용은 브라우저에 저장되지 않으며, 이메일 앱에서 직접 전송합니다. 이메일로 전달한 이름·연락처·문의 내용은 교육 상담 및 회신에 사용됩니다. 민감한 정보는 입력하지 마세요.</div><label class="consent"><input type="checkbox" name="개인정보 동의" value="동의" required><span>상담을 위한 개인정보 수집 및 이용에 동의합니다. <span class="required">*</span></span></label>`;
function applyForm(courseId='',audience='',organization=false) {
  const course=courseById(courseId);
  const date=new Date();const localDate=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,10);
  const common=`${field(organization?'담당자명':'이름','이름','text',true,'autocomplete="name" maxlength="80"')}${field('연락처','연락처','tel',true,'autocomplete="tel" inputmode="tel" pattern="[0-9+()\\s-]{8,20}" title="8~20자의 전화번호를 입력해 주세요"')}${field('이메일','이메일','email',true,'autocomplete="email" maxlength="150"')}`;
  const personal = `${common}${selectField('교육 대상','교육 대상',['시니어','기업','교육자','공무원','기타'],audience)}${selectField('신청 강의','신청 강의',[...NEXC.courses.map(c=>c.title),'과정 추천 상담'],course?.title||'과정 추천 상담')}${selectField('희망 교육 방식','희망 교육 방식',['온라인','오프라인','상관없음'])}${field('희망 교육 일정','희망 교육 일정','date',false,`min="${localDate}"`)}`;
  const org = `${field('기관명','기관명','text',true,'autocomplete="organization" maxlength="120"')}${common}${selectField('기관 유형','기관 유형',['기업','공공기관','학교','대학','지자체','교육기관','기타'])}${selectField('예상 교육 인원','교육 인원',['10명 이하','10~30명','30~50명','50~100명','100명 이상'])}<fieldset class="full"><legend>희망 강의 분야 <span class="required">*</span> <small>복수 선택 가능</small></legend><div class="checkbox-group">${['생성AI','AI 이미지','AI 영상','업무자동화','AI 리터러시','기타'].map(n=>`<label><input type="checkbox" name="희망 강의 분야" value="${n}">${n}</label>`).join('')}</div></fieldset>${selectField('희망 교육 형태','희망 교육 형태',['대면','온라인','혼합'])}${field('희망 날짜','희망 날짜','date',false,`min="${localDate}"`)}${selectField('교육 시간','교육 시간',['1시간','2시간','3시간','반일','종일','협의'])}`;
  openModal(organization?'기업·기관 강연 문의':'수강 상담 신청',`<p class="form-intro">${organization?'우리 조직에 필요한 교육을 알려주세요.':'관심 있는 강의와 희망 일정을 알려주세요.'} 작성 후 이메일 앱에서 내용을 확인하고 보내 주세요.</p><form id="inquiry-form" data-kind="${organization?'강연 문의':'수강 상담'}"><div class="form-grid">${organization?org:personal}<label class="full">문의 내용<textarea name="문의 내용" rows="4" maxlength="3000" placeholder="교육 목표나 궁금한 점을 자유롭게 적어주세요."></textarea></label></div>${consent}<p class="form-error" id="form-error" role="alert"></p><button class="button primary form-submit" type="submit">문의 내용 확인하기 ↗</button><p class="form-footnote">바로 상담하고 싶다면 <a href="tel:01026273771">010-2627-3771</a></p></form>`);
  $('#inquiry-form').addEventListener('submit',event=>{
    event.preventDefault();const form=event.currentTarget;
    if(organization&&!form.querySelector('input[name="희망 강의 분야"]:checked')){$('#form-error').textContent='희망 강의 분야를 하나 이상 선택해 주세요.';form.querySelector('input[name="희망 강의 분야"]').focus();return;}
    const data=new FormData(form);const lines=[];for(const name of new Set(data.keys()))lines.push(`${name}: ${data.getAll(name).join(', ')}`);
    const body=`[NEXC AI ${form.dataset.kind}]\n\n${lines.join('\n')}`;
    const subject=`NEXC AI ${form.dataset.kind} — ${data.get('이름')}`;
    openModal('문의 내용을 확인해 주세요',`<div class="review-notice"><strong>아직 문의가 전송되지 않았습니다.</strong><p>아래 내용을 확인한 뒤 이메일 앱에서 전송해 주세요. 이메일 앱이 없다면 내용을 복사해 e_iiias@naver.com으로 보내실 수 있습니다.</p></div><pre class="inquiry-preview">${escapeHTML(body)}</pre><div class="actions"><a class="button primary" id="email-send" href="mailto:e_iiias@naver.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}">이메일 앱에서 보내기 ↗</a><button class="button outline" id="copy-inquiry">내용 복사</button></div><p id="copy-status" class="copy-status" role="status"></p>`);
    $('#copy-inquiry').addEventListener('click',()=>copyText(body,$('#copy-status')));
    $('#email-send').addEventListener('click',()=>{$('#copy-status').textContent='이메일 앱에서 전송을 완료해 주세요. 이 사이트에서는 전송 여부를 확인할 수 없습니다.';});
  });
}
async function copyText(text,status){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);}else{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';$('#modal-body').append(area);area.select();if(!document.execCommand('copy'))throw new Error('copy');area.remove();}status.textContent='복사했습니다. 이메일 작성 화면에 붙여넣어 주세요.';}catch{status.textContent='자동 복사가 지원되지 않습니다. 위 내용을 선택해 직접 복사해 주세요.';}}

const lessonHTML=`<div class="lesson-content"><span class="status-label">무료 미니 레슨</span><p>좋은 질문에는 AI가 해야 할 일과 결과물의 기준이 담겨 있습니다. 다음 네 가지 요소로 첫 프롬프트를 작성해 보세요.</p><ol><li><strong>역할</strong> — 어떤 관점에서 답해야 하나요?<p>“너는 초보자에게 설명하는 AI 교육 강사야.”</p></li><li><strong>목표</strong> — 무엇을 얻고 싶나요?<p>“ChatGPT를 처음 사용하는 방법을 설명해 줘.”</p></li><li><strong>맥락</strong> — 대상과 상황은 무엇인가요?<p>“대상은 스마트폰만 사용하는 시니어야.”</p></li><li><strong>출력 형식</strong> — 어떤 형태가 필요한가요?<p>“쉬운 말로, 5단계 체크리스트로 정리해 줘.”</p></li></ol><div class="lesson-practice"><h3>직접 연습해 보세요</h3><p>위 예시의 대상과 목표를 자신의 상황에 맞게 바꿔 보세요. 답변이 너무 어렵다면 “예시를 하나 더 들어 줘”처럼 후속 질문을 이어가세요.</p></div><p>AI의 답변은 틀릴 수 있습니다. 중요한 정보는 신뢰할 수 있는 원문과 비교하고, 개인정보나 조직의 기밀은 입력하지 마세요.</p><a href="#course/generative" class="button primary" data-close>생성AI 강의 살펴보기 ↗</a></div>`;
function downloadChecklist(){const text='NEXC AI | AI 결과물 활용 체크리스트\n\n□ 사실과 숫자를 원문 출처와 비교했나요?\n□ 최신 정보인지 확인했나요?\n□ 개인이나 조직의 민감한 정보가 포함되어 있지 않나요?\n□ 이미지·문구 등의 이용 조건을 확인했나요?\n□ 대상과 목적에 맞는 표현인가요?\n□ 실제 사용 전에 사람이 최종 검토했나요?\n\nNEXC AI · 대표 장안선\n010-2627-3771 | e_iiias@naver.com';const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='NEXC-AI-활용-체크리스트.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function searchDialog(){openModal('어떤 배움을 찾고 계신가요?',`<label class="search-label" for="site-search">강의 · E-BOOK · 교육자료 검색</label><input id="site-search" type="search" placeholder="생성AI, 이미지, 영상, 업무자동화…" autocomplete="off"><div id="search-results" class="search-results" aria-live="polite"></div>`);const input=$('#site-search');const update=()=>{const query=input.value.trim().toLocaleLowerCase();const records=[...NEXC.courses.flatMap(c=>[{label:c.title,type:'강의',href:`#course/${c.id}`,text:c.category+' '+c.description+' '+c.topics.join(' ')},{label:c.book,type:'E-BOOK · 출간 준비 중',href:`#ebook/${c.id}`,text:c.category+' '+c.description}]),{label:'좋은 답변을 만드는 질문의 4가지 요소',type:'무료 교육자료',action:'lesson',text:'프롬프트 생성AI ChatGPT 무료 강의'},{label:'AI 결과물 활용 체크리스트',type:'무료 교육자료',action:'checklist',text:'자료 정확성 개인정보 다운로드'},{label:'강의 후기 공개 준비 중',type:'강의 후기',href:'#reviews',text:'수강생 경험 후기'}];const matches=records.filter(r=>(r.label+' '+r.text).toLocaleLowerCase().includes(query));$('#search-results').innerHTML=`<p class="search-count">${matches.length}개의 결과</p>`+(matches.length?matches.map(r=>r.href?`<a class="search-result" href="${r.href}" data-close><span>${r.type}</span><strong>${r.label}</strong><b>↗</b></a>`:`<button class="search-result" data-action="${r.action}"><span>${r.type}</span><strong>${r.label}</strong><b>↗</b></button>`).join(''):'<p class="empty-search">검색 결과가 없습니다. “생성AI” 또는 “이미지”처럼 다른 검색어를 입력해 보세요.</p>');};input.addEventListener('input',update);update();input.focus();}

document.addEventListener('click',event=>{
  const close=event.target.closest('[data-close]');if(close)closeModal();
  const target=event.target.closest('[data-action]');if(!target)return;
  const action=target.dataset.action;
  if(action==='apply')applyForm(target.dataset.course);
  if(action==='organization')applyForm('','',true);
  if(action==='search')searchDialog();
  if(action==='lesson')openModal('좋은 답변을 만드는 질문의 4가지 요소',lessonHTML);
  if(action==='checklist')downloadChecklist();
  if(action==='audience'){const a=audiences.find(a=>a.name===target.dataset.audience);openModal(`${a.name} 맞춤 AI 교육`,`<p>${a.text}</p><h3>이런 내용을 함께 배웁니다</h3><p>${a.topics}</p><p>현재 활용 수준과 교육 목적에 맞춰 과정과 속도를 조정합니다. 온라인·오프라인 진행 방식, 시간, 일정과 비용은 상담 후 안내합니다.</p><button class="button primary" id="audience-apply">맞춤교육 상담하기 ↗</button>`);$('#audience-apply').addEventListener('click',()=>applyForm('',a.name));}
  if(action==='book-inquiry'){const c=courseById(target.dataset.course);openModal('E-BOOK 출간 안내',`<p><strong>${c.book}</strong>은 출간 준비 중입니다.</p><p>가격, 최종 목차와 PDF 미리보기는 출간 후 안내됩니다. 현재 결제나 파일 다운로드는 제공하지 않습니다.</p><a class="button primary" href="mailto:e_iiias@naver.com?subject=${encodeURIComponent(c.book+' 출간 문의')}">출간 일정 문의하기 ↗</a>`);}
  if(action==='privacy')openModal('개인정보처리방침',`<div class="policy"><p>운영자: NEXC AI · 장안선<br>문의: e_iiias@naver.com / 010-2627-3771</p><h3>문의 양식과 이메일</h3><p>이 사이트의 문의 양식은 입력한 내용을 이메일로 작성할 수 있도록 돕습니다. 사이트 서버로 양식 데이터를 전송하거나 브라우저에 저장하지 않습니다. 이메일 앱에서 사용자가 직접 전송해야 운영자에게 전달됩니다.</p><h3>상담에 사용하는 정보</h3><p>이름, 연락처, 이메일, 교육 대상, 희망 과정, 일정 및 문의 내용을 상담과 회신 목적으로 사용합니다. 기관 문의에는 기관명, 인원 및 교육 조건이 포함될 수 있습니다. 동의를 거부할 수 있으며, 이 경우 양식 이용이 제한됩니다.</p><h3>보유 및 삭제</h3><p>이메일로 접수한 문의 정보는 상담 목적 달성 후 지체 없이 삭제합니다. 다만 법령에 별도 보관 의무가 있는 정보는 해당 기간 동안 보관합니다. 열람·정정·삭제 요청은 위 연락처로 보내 주세요.</p><h3>외부 서비스</h3><p>화면의 글꼴은 Google Fonts에서 불러옵니다. 선택한 이메일 서비스 이용 시 해당 서비스의 개인정보 정책이 적용됩니다. 방문 통계용 추적 도구와 광고 쿠키는 사용하지 않습니다.</p></div>`);
  if(action==='terms')openModal('사이트 이용 안내',`<div class="policy"><p>NEXC AI는 생성AI·이미지·영상·업무자동화 교육과 기업·기관 맞춤 강연을 안내합니다.</p><h3>교육 신청과 확정</h3><p>문의 양식 작성은 수강 확정이나 결제가 아닙니다. 이메일로 문의를 보내신 후 일정, 비용, 교육 방식, 취소 및 환불 조건을 개별 안내받아 확정합니다.</p><h3>전자책</h3><p>현재 출간 준비 중이며, 결제와 PDF 제공은 시작되지 않았습니다. 판매 개시 시 상품 정보와 이용 조건을 안내합니다.</p><h3>학습 자료 이용</h3><p>사이트의 무료 자료는 개인 학습에 활용할 수 있습니다. 재판매나 상업적 재배포는 운영자에게 문의해 주세요. AI 활용에 따른 특정 수익이나 성과를 보장하지 않습니다.</p></div>`);
});

function renderDetail(type,id){const c=courseById(id);if(!c){$('#detail-view').innerHTML='<div class="not-found"><h1>페이지를 찾을 수 없습니다.</h1><p>강의 목록에서 다시 선택해 주세요.</p><a class="button primary" href="#courses">강의 목록으로</a></div>';return;}
  const book=type==='ebook';document.title=`${book?c.book:c.title} | NEXC AI`;
  const breadcrumb=`<nav class="breadcrumb" aria-label="현재 위치"><a href="#home">홈</a><span>/</span><a href="#${book?'ebooks':'courses'}">${book?'E-BOOK':'AI 강의'}</a><span>/</span><span>${c.category}</span></nav>`;
  const courseInfo=`<div class="detail-main"><section><h2>이런 분께 추천합니다</h2><p>${c.audience}</p></section><section><h2>교육 목표</h2><p>${c.goal}</p></section><section><h2>직접 해보며 배우는 커리큘럼</h2><p>아래 내용은 기본 교육 구성입니다. 수준과 교육 목적에 맞춰 조정합니다.</p><ol class="curriculum">${c.topics.map((t,i)=>`<li><span>0${i+1}</span><div><strong>${t}</strong><p>개념 이해 · 활용 사례 · 직접 실습</p></div></li>`).join('')}</ol></section><section><h2>교육 안내</h2><dl class="info-table"><div><dt>교육 방식</dt><dd>온라인·오프라인 실습 중심 교육</dd></div><div><dt>교육 시간·일정</dt><dd>대상, 수준, 교육 목표에 따라 상담 후 확정</dd></div><div><dt>교육 대상</dt><dd>시니어 · 기업 · 교육자 · 공무원</dd></div><div><dt>수강료</dt><dd>교육 인원·시간·형태에 따라 개별 안내</dd></div><div><dt>준비물</dt><dd>실습용 기기 및 계정은 교육 확정 시 안내</dd></div></dl></section><section><h2>강의 후기</h2><p>수강생의 동의를 받은 실제 후기 공개를 준비 중입니다.</p></section><section class="related-book"><div><span class="eyebrow">RELATED E-BOOK</span><h3>${c.book}</h3><p>강의와 이어지는 실전 학습 가이드 · 출간 준비 중</p></div><a class="button outline" href="#ebook/${c.id}">E-BOOK 구매 안내 ↗</a></section></div>`;
  const bookInfo=`<div class="detail-main"><section><h2>이 책에서 배우는 것</h2><p>${c.goal}</p></section><section><h2>예정 목차</h2><p>출간 준비 중인 구성으로, 최종 목차는 변경될 수 있습니다.</p><ol class="curriculum">${c.topics.map((t,i)=>`<li><span>0${i+1}</span><strong>${t}</strong></li>`).join('')}</ol></section><section><h2>추천 대상</h2><p>${c.audience}</p></section><section><h2>미리보기</h2><div class="review-notice"><p>본문 PDF 미리보기는 출간 후 제공할 예정입니다. 먼저 무료 학습 자료를 활용해 보세요.</p><button class="text-link" data-action="lesson">무료 미니 레슨 읽기 ↗</button></div></section><section><h2>저자 소개</h2><h3>장안선 · NEXC AI 대표</h3><p>생성AI, AI 이미지, AI 영상, 업무자동화 등 현장에서 활용할 수 있는 AI 활용법을 쉽고 실전적으로 교육합니다.</p></section><section class="related-book"><div><span class="eyebrow">RELATED CLASS</span><h3>${c.title}</h3><p>실습과 함께 배우고 싶다면 관련 강의를 살펴보세요.</p></div><a class="button outline" href="#course/${c.id}">관련 강의 보기 ↗</a></section></div>`;
  $('#detail-view').innerHTML=`${breadcrumb}<div class="detail-hero"><div><span class="eyebrow">${book?'NEXC AI E-BOOK':'NEXC AI PRACTICAL CLASS'} / ${c.category}</span><h1>${book?c.book:c.title}</h1><p>${c.description}</p><div class="actions"><button class="button primary" data-action="${book?'book-inquiry':'apply'}" data-course="${c.id}">${book?'출간 일정 문의':'강의 신청하기'} ↗</button>${book?'<span class="status-label">출간 준비 중 · 가격 미정</span>':`<a class="button outline" href="#ebook/${c.id}">E-BOOK 구매 안내</a>`}</div></div><div class="detail-art ${c.color}"><span>${book?'PRACTICAL GUIDE':'LEARN. CREATE. GROW.'}</span><strong>${c.symbol}</strong><b>${c.category}</b><span>${book?'PDF E-BOOK · 장안선 지음':'NEXC AI · 실전 중심 교육'}</span></div></div><div class="detail-layout">${book?bookInfo:courseInfo}<aside class="detail-aside"><span class="eyebrow">${book?'CONTINUE LEARNING':'START YOUR JOURNEY'}</span><h3>${book?'나만의 속도로 배우세요.':'배움의 시작을 함께합니다.'}</h3><p>${book?'전자책은 출간 준비 중입니다. 판매 일정과 제공 방식은 확정 후 안내합니다.':'관심 과정과 희망 일정을 알려주시면 적합한 교육을 안내합니다.'}</p><button class="button primary" data-action="${book?'book-inquiry':'apply'}" data-course="${c.id}">${book?'출간 문의하기':'강의 신청하기'} ↗</button><button class="button outline" data-action="organization">강연 문의하기 ↗</button><a href="tel:01026273771">010-2627-3771</a></aside></div>`;
}
function route(){const hash=decodeURIComponent(location.hash.slice(1)||'home');const parts=hash.split('/');const detail=parts[0]==='course'||parts[0]==='ebook';$('#home-view').hidden=detail;$('#detail-view').hidden=!detail;if(detail){renderDetail(parts[0],parts[1]);window.scrollTo({top:0,behavior:'instant'});}else{document.title='NEXC AI — 당신의 내일을 바꾸는 AI 교육';const target=document.getElementById(hash);if(target)requestAnimationFrame(()=>target.scrollIntoView({behavior:'instant',block:'start'}));}if(modal.open)closeModal();}
window.addEventListener('hashchange',route);route();
